// <auto-generated />
namespace E_Reviu_LKBUN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class responses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(responses));
        
        string IMigrationMetadata.Id
        {
            get { return "202202121632405_responses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
